site_name: ModularConnect.io
nav:
    - Home: index.md
    - About: about.md
site_url: https://modularconnect.github.io/ModularConnect.github.io/docs/index.md
site_description: A strong and powerful middleware to automate business processes
site_author: ModularConnect.io

repo_url: https://modularconnect.github.io/ModularConnect.github.io/



theme:
    name: flatly

markdown_extensions:
    - toc:
        permalink: '#'

plugins:
    - search
